export const LOGIN_TITLE = "SignIn | ShivInfotech";
export const EMAIL_LABEL = "Email";
export const PASSWORD_LABEL = "Password";
export const PLACEHOLDER_EMAIL = "Enter email";
export const PLACEHOLDER_PASSWORD = "Enter Password";
export const FORGOT_PASSWORD = "Forgot password?";
export const WELCOME_BACK = "Welcome Back!";
export const SIGN_IN_MESSAGE = "Sign in to continue to Shiv Infotech.";
export const SUCCESS_MESSAGE = "Login Success!";
export const ERROR_MESSAGE = "An unexpected error occurred.";
export const ERROR_CHECK_CREDENTIALS = "Check your email or password";
export const PLEASE_ENTER_YOUR_EMAIL ="Please Enter Your Email";
export const PLEASE_ENTER_YOUR_PASSWORD ="Please Enter Your Password";
export const LOADING = "Loading...";
export const SIGNIN = "Sign In";
export const EMAIL_SENT_SUCCESS = "Reset link sent to your mailbox, check there first";
export const RESET_LINK_SENT = "Reset link sent to your mailbox!";
export const FAILED_TO_SENT_RESET_LINK = "Failed to send reset link.";
export const FORGOT_PASSWORD_TITLE = "Reset Password | ShivInfotech";
export const ENTER_YOUR_EMAIL_AND_INSTRUCTIONS_WILL_BE_SENT  = "Enter your email and instructions will be sent to you!"; 
export const SENDING = "Sending..."
export const SEND_RESET_LINK="Send Reset Link"
export const WAIT_I_REMEMBER_MY_PASS="Wait, I remember my password... "
export const CLICK_HERE = "Click here "
export const RESET_PASSWORD_WITH_SI="Reset password with ShivInfotech"
export const PASSWORD_TYPE = "password"
export const OTP_REQUIRED = "OTP is required"
export const OTP_LABEL = "OTP";
export const PLACEHOLDER_OTP = "Enter OTP";
export const NEW_PASSWORD_LABEL = "New Password";
export const PLACEHOLDER_NEW_PASSWORD = "Enter new password";
export const CONFIRM_PASSWORD_LABEL = "Confirm Password";
export const PLACEHOLDER_CONFIRM_PASSWORD = "Confirm new password";
export const UPDATE_PASSWORD_TITLE = "Update Password | ShivInfotech";
export const PASSWORD_UPDATED_SUCCESS = "Password updated successfully!";
export const EMAIL_REQUIRED = "Email is required.";
export const INVALID_EMAIL = "Invalid email address.";
export const PASSWORDS_MUST_MATCH = "Passwords must match.";
export const NEW_PASSWORD_REQUIRED = "New password is required.";
export const CONFIRM_PASSWORD_REQUIRED = "Confirm password is required.";
export const ERROR_DURING_PASS_UPDATE = "Error during password update."
export const PASSWORD_6_CHAR = "Password must be at least 6 characters"
export const UPDATING = "Updating..."
export const UPDATE_PASSWORD="Update Password"
export const TEXT_LABEL = "text"
export const PLEASE_ENTER_YOUR_DETAILS_TO_UPDATE_PASS = "Please enter your details to update your password."
export const USER ="User"
export const USER_MAIL_EXAMPLE = "user@example.com"
export const PROFILE_VALUE = "profile"
export const SETTINGS_TITLE = "Profile Settings | ShivInfotech";
export const PROFILE_INFORMATION = "Profile Information";
export const CHANGE_PASSWORD_TITLE = "Change Password";
export const CURRENT_PASSWORD_LABEL = "Current Password";
export const NEW_PASSWORD_REQUIRED_MESSAGE = "New password is required.";
export const CONFIRM_PASSWORD_REQUIRED_MESSAGE = "Please confirm your new password.";
export const PASSWORD_UPDATED_SUCCESS_MESSAGE = "Your password has been successfully updated!";
export const ERROR_UPDATING_PROFILE = "Error updating profile. Please try again.";
export const ERROR_UPDATING_PASSWORD = "Error updating password. Please check your inputs.";
export const PASSWORD_CHANGE_SUCCESS = "Your password has been changed successfully!";
export const PASSWORD_CHANGE_ERROR = "There was an error changing your password.";
export const EDIT_PROFILE = "Edit Profile";
export const UPDATE_PROFILE = "Update Profile";
export const PROFILE_IMAGE_UPDATE_SUCCESS = "Profile image updated successfully!";
export const ERROR_UPDATING_IMAGE = "Error updating profile image. Please try again.";
export const PASSWORD_VALUE = "password"
export const CHANGING_PASSWORD_TEXT = "Changing Password"
export const CHANGE_PASSWORD_BUTTON = "Change Password"
export const CURRENT_PASSWORD_IS_REQUIRED  ="Current password is required"
export const NAME = "Name"
export const ENTER_YOUR_NAME = "Enter Your Name"
export const PHONE_NUMBER = "Phone Number"
export const ENTER_YOUR_PHONE_NUMBER = "Enter Your Phone Number"
export const ENTER_YOUR_EMAIL_ADDRESS = "Enter Your Email Address"
export const ENTER_CURRENT_PASSWORD = "Enter Current Password"
export const ENTER_NEW_PASSWORD = "Enter New Password"
export const CONFIRM_NEW_PASSWORD = "Confirm New Password"

